Repository rago89/Group-6-Study-Guide, pull requests merged in 2020-11, with the labels that each got.

#9 Adding images on contact page
  images/fb.png
  images/instagram.jpg
  images/twitter.png
Labels: group-6 task-1

#11 adding about.html codes
  about.html
Labels: group-6 tast-3

#13 fix deplacement main content and add title
  README.md
  css/style.css
  index.html
Labels: enhancement

#12 css update codes
  css/style.css
  index.html
Labels: group-6 tast-3

#10 adding contact.html codes
  contact.html
Labels: group-6 task-2
